async function fetchEncryptDataOfAccount(publicKey) {
  const fakeCertificateData =
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper massa nec massa semper ullamcorper. Nunc id convallis ligula. Aliquam porta elit sit amet molestie gravida. Nulla lobortis ultricies sapien in commodo. Cras sit amet augue id nulla commodo semper. Mauris quis sapien elit. Aliquam vitae orci fringilla tortor bibendum condimentum sit amet nec mauris. Donec dapibus volutpat massa, id sollicitudin tortor rhoncus nec. Aliquam congue diam vitae quam malesuada interdum. Ut malesuada et est vehicula vulputate. Donec hendrerit ultrices dictum. Pellentesque pulvinar pulvinar urna, facilisis egestas nibh mollis vel. Nullam vitae scelerisque dui. Morbi non porta libero";
  const text =
    "Sed at eleifend mi. Cras fermentum dolor ac quam tincidunt suscipit. Mauris venenatis, turpis at placerat tristique, quam nibh egestas sem, a finibus tortor arcu vel lectus. Phasellus ullamcorper, ex vitae porta pellentesque, est massa pulvinar sem, sit amet molestie urna libero et massa. Quisque sollicitudin auctor nibh, non tincidunt ex ultrices quis. Morbi vestibulum vestibulum sapien. Nullam id egestas velit. Aenean et nibh vehicula, dapibus nisl nec, accumsan est. In imperdiet quam vitae velit accumsan rhoncus. Cras sagittis magna ligula, vitae malesuada enim aliquet vel.In in nisl eu ante efficitur pharetra. Quisque ultricies dolor et odio egestas, sit amet ultrices eros posuere. Donec a pulvinar mauris, a pellentesque ligula. Integer malesuada ornare velit. Donec in fringilla lorem. Aliquam blandit velit vitae sem fringilla rhoncus. Sed vulputate lorem et iaculis mattis. Aenean id fermentum tellus. Proin dignissim vehicula est vitae mollis. Proin fermentum, felis ac gravida placerat, justo mauris vehicula lorem, et fermentum lectus urna quis orci. Aliquam lacinia massa sit amet quam ultricies suscipit.Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce ligula mauris, fringilla eget placerat nec, iaculis ac massa. Duis pellentesque et elit non accumsan. Proin maximus nibh sed lacinia dictum. Nulla volutpat nunc ac leo iaculis, a pharetra ante malesuada. Vivamus placerat nisi rhoncus erat tempor hendrerit. Vivamus auctor fermentum felis vitae vestibulum. Nam sit amet odio eu arcu fermentum dapibus vel sed massa. Nulla condimentum justo magna, at tristique enim ultrices eget. Nullam non tellus augue. Morbi eget felis sapien.Maecenas dapibus ultricies massa eget ullamcorper. Duis mi nibh, iaculis at volutpat ac, ullamcorper sed quam. Duis vestibulum elit quis eros volutpat volutpat. Duis tincidunt pretium ligula eu convallis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin pretium, nisl ac luctus fermentum, urna risus luctus eros, eget mattis risus lectus eget est. Phasellus a condimentum risus, nec finibus diam. Cras condimentum nunc non metus ullamcorper pretium. Suspendisse justo neque, egestas in lacus ut, hendrerit aliquam leo. Phasellus feugiat ultricies turpis a tincidunt. Mauris quis aliquam libero. Nam pellentesque sed mauris vitae dictum. Nunc nibh tellus, bibendum id molestie at, dignissim vel dolor.";
  const fakeSubjectPointList = text.split(".");
  return Promise.resolve({ encryptedDataOfAccount: { certificate: fakeCertificateData, subjectPointList: fakeSubjectPointList } });
}

module.exports = { fetchEncryptDataOfAccount };
